# Site settings
title: "Noel Csomay-Shanklin"
default_header: ""
url: "https://noelc-s.github.io"
future: true

# Secondary Parameters
baseurl: "/website"
header-img: img/home-bg-crop.png
headercolor: "#FFFFFF"
logo: /website/img/Noel_headshot.png

# Tertiary Parameters
github_username:  noelc-s
project_repository: website
#disqus_shortname: noelc-s
g-analytics: G-QKMYN2YHYF
altmetric: true

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 2000
paginate_path: "feed/page:num"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg-crop.png"

# Prose Settings
prose:
  ignore: ['feed.xml', '/stl', '/ply', '/js', '/plugin', '/lib', '/projectors', '_layouts', '/_includes', 'Gruntfile.js', 'package.json', 'proselinks.jsonp', 'ppanchor.matin', '.gitignore', '/search', '/css', '/img', 'favicon.png','_data/*.json','LICENSES.md','README.md','colorscheme.scss','members.html','mentions.html','index.html']
  siteurl: 'http://projectpages.github.io/project-pages/'
  ispp: true
  media: 'img'
  metadata:
    projects:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Project"
          value: ""           
    _posts:
      - name: "subtitle"
        field:
          authorelement: "text"
          label: "Sub-Title (Short Description)"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Choose Layout"
          placeholder: "Layouts"
          options:
            - name: "Post"
              value: "post"
            - name: "Slide"
              value: "slide"
            - name: "Projector"
              value: "projector"
            - name: "Notebook"
              value: "notebook"
            - name: "Ply Surface"
              value: "plysurface"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags (seperate with whitespace)"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Project"
          value: ""    
      - name: "horizontal"
        field:
          element: "hidden"
          value: </section></section><section markdown="1" data-background="http://projectpages.github.io/project-pages/img/slidebackground.png"><section markdown="1">
      - name: "vertical"
        field:
          element: "hidden"
          value: </section><section markdown="1">
      - name: "slideinit"
        field:
          element: "hidden"
          value: <section markdown="1" data-background="http://projectpages.github.io/project-pages/img/slidebackground.png"><section markdown="1">
      - name: "theme"
        field:
          element: "select"
          label: "Theme (Slide)"
          placeholder: "Theme (Slide)"
          options:
            - name: "Beige"
              value: "beige"
            - name: "Blood"
              value: "blood"
            - name: "Moon"
              value: "moon"          
            - name: "Night"
              value: "night"
            - name: "Sky"
              value: "sky"
            - name: "Solarized"
              value: "solarized"             
      - name: "trans"
        field:
          element: "select"
          label: "Transition (Slide)"
          placeholder: "Transition (Slide)"
          options:
            - name: "Cube"
              value: "cube"
            - name: "Page"
              value: "page"
            - name: "Concave"
              value: "concave"          
            - name: "Linear"
              value: "linear"
            - name: "Fade"
              value: "fade"
            - name: "None"
              value: "none"             
      - name: "visualworkflow"
        field:
          element: "checkbox"
          label: "Visual Workflow Chart (Some Layouts)"
          value: "true"

          # theme: jekyll-theme-cayman
# theme: minimal-mistakes-jekyll
# minimal_mistakes_skin: "dark" 

remote-theme: "mmistakes/minimal-mistakes@4.24.0"

# plugins: 
  # - jekyll-include-cache
